name: 'Publish to PyPI'
description: 'Build and publish Python package to PyPI using uv and trusted publishing'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set version from release tag
      shell: bash
      run: |
        VERSION="${GITHUB_REF_NAME}"
        VERSION="${VERSION#v}"
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        echo "Set version to $VERSION"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Build package
      shell: bash
      run: uv build

    - name: Publish to PyPI
      shell: bash
      run: uv publish
